### PR TITLE
Bugfix #102465

### PR DESCRIPTION
**Pull request by adamlatchem**
Apply fix from https://bugs.mysql.com/bug.php?id=102465

### CODE REVIEW

**Comment by Farkie** [comment]
@adamlatchem would you be able to re-submit or mind if I resubmit this patch? This issue has been on workbench for so long, I just want it fixed in then next version!

**Comment by adamlatchem** [comment]
Hi @Farkie you are very welcome to submit the patch yourself. I am amazed it was not taken from the original bug report which is why I tried this route - the OCA was a step too far for me. Thanks for taking up the torch.

**Comment by Farkie** [comment]
Hi @adamlatchem , thanks - I've signed the OCA and it's awaiting approval. Once that's done I'll resubmit. Thanks for your reply!

**Comment by deltafactory** [comment]
Can someone *please* merge this fix?

**Comment by srl295** [comment]
see also #35 which was accepted

**Pull request closed without merging**
